### ISSUE TITLE
ember-cli-ember-table ? 

### ISSUE THREAD

**Issue by yanzixiang** [Addepar/ember-table-addon#11]
please let us know ,
which addon should we use ?
do u know each other ?

**Comment by azirbel** [comment]
`ember-cli-ember-table` was made by @intuitivepixel a while ago and was an important solution for people who were anxious to move to ember-cli. It also paved the way for a lot of work here. We're really thankful for his help!

With that library in place, we were able to spend some time e.g. rebuilding the demo app and providing backwards compatibility. This repository is the official version and will soon replace `ember-table`.

I think we've just crossed the line where I'd recommend people use `ember-table-addon` instead of `ember-cli-ember-table`. It's still new, but if you run into problems I'll be happy to fix them. I've tested this library lightly and it seems to work.

See https://github.com/Addepar/ember-table/issues/300 for more information on this project's status.
